_wandb:
    value:
        cli_version: 0.22.3
        e:
            cbtmocsainrwhsrl8vrky34brp55xqzr:
                codePath: Transformer/ratiosweep.py
                codePathLocal: ratiosweep.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "424284069888"
                        used: "224898449408"
                email: autoshin0322@gmail.com
                executable: /home/stud_homes/s6010479/miniconda3/envs/posevit/bin/python
                git:
                    commit: c92741508ceaea4fb4cf3b909cd6d830f004ceb6
                    remote: git@github.com:autoshin0322/Jayproject.git
                host: eschar
                memory:
                    total: "67513634816"
                os: Linux-5.4.0-200-generic-x86_64-with-glibc2.31
                program: /home/stud_homes/s6010479/Jayproject/Transformer/ratiosweep.py
                python: CPython 3.10.18
                root: /home/stud_homes/s6010479/Jayproject/Transformer
                startedAt: "2025-11-12T15:18:04.377911Z"
                writerId: cbtmocsainrwhsrl8vrky34brp55xqzr
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.10.18
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
alpha:
    value: 1
batch_size:
    value: 32
epochs:
    value: 20
lr:
    value: 0.00050701
run_id:
    value: 0
seed:
    value: 42
